### ISSUE TITLE
riscv-gcc failed to build on 10.10

### ISSUE THREAD

**Issue by schirice** [ucb-bar/homebrew-riscv#1]
Good evening,

I have been trying to build risk-gcc and it fails with "configure: error: C preprocessor "/lib/cpp" fails sanity check". I have included a gist-log at https://gist.github.com/bc7df004ee8e5dd722e2

Any idea what causes this error?

thanks,
-silviu

**Comment by sbeamer** [comment]
I just updated the tools to work with Yosemite (b8a7d16) and made new bottles (7fce13a0). Hopefully this fixes your issue. Please confirm.

**Comment by schirice** [comment]
Scott,

That fixed the issues I was having and I was able to successfully build the tools.
Thanks,
-silviu
